yarnPath: .yarn/releases/yarn-2.3.3.cjs
packageExtensions:
  "@vue/cli-service@*":
    dependencies:
      vue-cli-plugin-vuetify: "*"
      vuetify-loader: "*"
      vuetify: "*"
      vue: "*"
  "bootstrap-vue@*":
    dependencies:
      vue: "*"
  "vue-slider-component@*":
    dependencies:
      vue: "*"
  "express@*":
    dependencies:
      pug: "*"


      