packageExtensions:
  "@vue/cli-service@*":
    dependencies:
      vue: "*"
      vue-cli-plugin-vuetify: "*"
      vuetify: "*"
      vuetify-loader: "*"
  bootstrap-vue@*:
    dependencies:
      vue: "*"
  express@*:
    dependencies:
      pug: "*"
  vue-slider-component@*:
    dependencies:
      vue: "*"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
