version: "3.8"
services:
  spoke_111:
    container_name: spoke_111
    build: ../coda19-site-api
    environment:
      - CODA19_SITE_API_HUB_API_URL=http://hub:8080/
      - CODA19_SITE_API_HOSPITAL_CODE=111
      - CODA19_SITE_API_SERVER_PORT=5418
    depends_on:
      - hub
  spoke_112:
    container_name: spoke_112
    build: ../coda19-site-api
    environment:
      - CODA19_SITE_API_HUB_API_URL=http://hub:8080/
      - CODA19_SITE_API_HOSPITAL_CODE=112
      - CODA19_SITE_API_SERVER_PORT=5418
    depends_on:
      - hub
  hub:
    container_name: hub
    build: ../coda19-hub-api
    environment:
      - CODA19_HUB_API_SERVER_PORT=8080
    ports:
      - 8080:8080
  # If you reenable dash, it won't work right away. URL in ".env" need to be changed to localhost:8080
  # and need docker-compose up --build to rebuild node app.
  #dash:
    #container_name: dash
    #build: ../coda19-hub-dashboard
    #ports:
    #  - 3000:8080
    #depends_on:
    #  - hub
